# Generated by Django 4.2.5 on 2026-01-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.BigAutoField(default=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
